# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Codility' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Codility
  
  pod 'RealmSwift'
  pod 'Alamofire', '~> 4.2.0'
  pod 'SwiftyJSON'
  pod 'MFCard'
  pod 'EPContactsPicker'
  pod 'RNCryptor', '~> 5.0'
  pod 'QRCode'
  pod 'Instructions', '~> 1.0.0'
  pod 'AMPopTip'
  
end
